server:
  port: 8001

spring:
  application:
    name: short-link-project
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  jackson:
    time-zone: Asia/Shanghai
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  mvc:
    view:
      prefix: /templates/
      suffix: .html

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

short-link:
  domain:
    default: leecoder.com:8001
  stats:
    locale:
      amap-key: e11655972d2a39b403fc306eae51040c
  goto-domain:
    white-list:
      enable: true
      names: '力扣平台,知乎,掘金,博客园'
      details:
        - leetcode.cn
        - zhihu.com
        - juejin.cn
        - cnblogs.com

rocketmq:
  name-server: common-rocketmq-dev.magestack.cn:9876
  producer:
    group: short-link_project-service_stats-save_pg_jeiko
    topic: short-link_project-service_topic_jeiko
    send-message-timeout: 2000
    retry-times-when-send-failed: 1
    retry-times-when-send-async-failed: 1
  consumer:
    group: short-link_project-service_stats-save_cg_jeiko

